package main

import (
	"testing"

	"golang.org/x/tour/tree"
)

func TestWalk(t *testing.T) {
	k := 3
	max := 10 // max random value generated by tree.New()
	tr := tree.New(k)
	ch := make(chan int, max)
	Walk(tr, ch)

	if cap(ch) != max {
		t.Errorf("channel's capacity shoud be %d but is %d\n", max, cap(ch))
		t.FailNow()
	}

	for i := 0; i < max; i++ {
		e := (i + 1) * k
		if v := <-ch; v != e {
			t.Errorf("channel's value %d is the expected value %d\n", v, e)
			t.FailNow()
		}
	}

}

func TestSame(t *testing.T) {
	t1 := tree.New(1)
	t2 := tree.New(1)
	t3 := &tree.Tree{ // one node more
		Left:  t2,
		Value: 12,
		Right: nil,
	}
	tt := []struct {
		name   string
		trees  []*tree.Tree
		result bool
	}{
		{"t1 equals t2", []*tree.Tree{t1, t2}, true},
		{"t1 equals t1", []*tree.Tree{t1, t1}, true},
		{"t1 is not equal t3", []*tree.Tree{t1, t3}, false},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {

			status := "equivalent"
			if !tc.result {
				status = "different"
			}

			if Same(tc.trees[0], tc.trees[1]) != tc.result {
				t.Errorf("%v\nand\n%v\nshould be %v\n", tc.trees[0], tc.trees[1], status)
				t.FailNow()
			}
		})
	}
}
