package main

import (
	"testing"

	"golang.org/x/tour/tree"
)

func TestWalk(t *testing.T) {
	k := 3
	max := 10 // max random value generated by tree.New()
	tr := tree.New(k)
	ch := make(chan int, max)
	Walk(tr, ch)

	if cap(ch) != max {
		t.Errorf("channel's capacity shoud be %d but is %d\n", max, cap(ch))
		t.FailNow()
	}

	for i := 0; i < max; i++ {
		e := (i + 1) * k
		if v := <-ch; v != e {
			t.Errorf("channel's value %d is the expected value %d\n", v, e)
			t.FailNow()
		}
	}

}

func TestSameWithEquivalentTrees(t *testing.T) {
	t1 := tree.New(1)
	t2 := tree.New(1)
	tt := []struct {
		name   string
		trees  []*tree.Tree
		result bool
	}{
		{"t1 equals t2", []*tree.Tree{t1, t2}, true},
		{"t1 equals t1", []*tree.Tree{t1, t1}, true},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			if !Same(tc.trees[0], tc.trees[1]) {
				t.Errorf("%v should equivalent with %v\n", tc.trees[0], tc.trees[1])
				t.FailNow()
			}
		})
	}
}

func TestSameWithDifferentDepthTrees(t *testing.T) {
	t1 := tree.New(1)
	t2 := tree.New(1)
	t3 := &tree.Tree{ // t3 will be longer than t1, it's t2 + one single root node
		Left:  t2,
		Value: 12,
		Right: nil,
	}
	if Same(t1, t3) {
		t.Errorf("t1 %v should be different with t3 %v\n", t1, t3)
		t.FailNow()
	}
}
